# Generated by Django 4.0.4 on 2022-05-30 16:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('myvspjapp', '0002_alter_files_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='files',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='taggings',
        ),
        migrations.AlterField(
            model_name='files',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
    ]
